version: "3.8"

services:
  app_api:
    build:
      context: backend
      dockerfile: Dockerfile
    image: app_api
    container_name: app_api
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-tier
    restart: always
  app_ui:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: app_ui
    container_name: app_ui
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    networks:
      - app-tier
    restart: always
    depends_on:
      - app_api

volumes:
  mysql-data:
    driver: local
networks:
  app-tier:
    driver: bridge
